### ISSUE TITLE
CORs blocked

### ISSUE THREAD

**Issue by KarthikS373** [harshmangalam/hydrogen-solidjs-client#12]
**Issue**
API calls are blocked. (CORS header ‘Access-Control-Allow-Origin’ missing)

![image](https://user-images.githubusercontent.com/96634646/193357907-572a60a6-bc5c-4214-90c1-b673c95ff3dd.png)

**Environment**
Browser: Firefox version 102.0.1
Enhanced tracking protection ON (does not work even with Enhanced tracking protection OFF)

**Comment by harshmangalam** [comment]
@KarthikS373  working fine in firefox. In which environment are you checking dev or prod ?

**Comment by KarthikS373** [comment]
> @KarthikS373 working fine in firefox. In which environment are you checking dev or prod ?

It was in production mode.

**Comment by harshmangalam** [comment]
Okay, https://hydrogen-solid.vercel.app/ url is working fine without any CORS block.
