### ISSUE TITLE
Add tooltip

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#13]
Add tooltip in post card icons and icon button
- Delete icon
- Post privacy icon
- Like icon button
- Comment icon button

**Comment by somenath203** [comment]
I want to contribute to this project. Can you please guide me on how I can do it?

**Comment by harshmangalam** [comment]
Sure

**Comment by somenath203** [comment]
Are there any specific guidelines regarding the pull request and the code submission?

**Comment by harshmangalam** [comment]
Open `components > posts > PostCard` folder and add proper title in icon button.

**Comment by harshmangalam** [comment]
> Are there any specific guidelines regarding the pull request and the code submission?

Most of the time reuse the existing component to fullfill your requirements and follow the folder structure to add new components.

**Comment by somenath203** [comment]
ok, got it, thanks for the reply.

**Comment by somenath203** [comment]
Both the client and the server is running but somehow, both are not connected with each other. I am unable to find the problem. Can you please help me?

**Comment by harshmangalam** [comment]
Do one thing add `.env` file in root and copy every thing from `.env.example`  and use production endpoint this way you do not need to setup backend on local.
`.env`

```
VITE_ENDPOINT=https://hydrogen-harsh.herokuapp.com/api

```

**Comment by somenath203** [comment]
Whenever I am importing any external npm package, then, the whole application is going inside an infinite loop.

Can you please tell how to resolve this issue please?

**Comment by harshmangalam** [comment]
Can you show me the log and gif.

**Comment by somenath203** [comment]
I recently deleted the project and then again re-installed it. The main issue which I am facing is whenever I am using ```npm install``` to install all the dependencies, then, it is giving this error
![Screenshot (151)](https://user-images.githubusercontent.com/81456073/193399922-0a316ab8-578a-4d36-917a-9152e2785fd0.png)

But, when I am using ```yarn```, then, everything is working fine and all the dependencies are getting installed.

After this, when I am installing an external package and then importing it any file, then, I am getting this error
![Screenshot (150)](https://user-images.githubusercontent.com/81456073/193399983-ad2d2063-d372-4f7c-9e2c-d8bf0e535acf.png)

**Comment by harshmangalam** [comment]
Remove node_module and any lock  related files like pnpm-lock.yaml etc...
Install pnpm using  `npm i  -g pnpm`
then install package using pnpm `pnpm i`
then run  `pnpm run dev`

**Comment by somenath203** [comment]
The main problem that is occurring is VITE is unable to find ```react``` and this is the reason why on importing any react-based npm package inside any component, the whole application is breaking.
![Screenshot (152)](https://user-images.githubusercontent.com/81456073/193401887-631ca58b-8e49-4b19-94f3-27c0bd127126.png)

**Comment by harshmangalam** [comment]
This is not react based project this is build on top of Solidjs

**Comment by somenath203** [comment]
Got it.

**Comment by somenath203** [comment]
I have successfully added the tooltips but when I am going to push the code, then, its saying ```remote: Permission to harshmangalam/hydrogen-solidjs-client.git denied to somenath203.```

**Comment by somenath203** [comment]
I have submitted my pull request for this project. You can now please check it.
