### ISSUE TITLE
Enhance image accessibility

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#15]
Enhance  image accessibility in Post card by adding
- Aspect ratio in image
- Proper alt attribute in image
- Width and Height in image

**Comment by SupOrg** [comment]
Hey @harshmangalam can you please assign this to me ? :)

**Comment by Jem256** [comment]
Hey, I would like to work on this as well

**Comment by harshmangalam** [comment]
@Jem256  you can continue...
