### ISSUE TITLE
Enhance login button UI

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#2]
Add Enhancement in login button

-  Add spinner in login button while loading...
-  Disable button during loading... 
-  Change  disable button background

**Comment by ashishpetwal** [comment]
I would like to work on this issue! Kindly issue this task to me...

**Comment by ashishpetwal** [comment]
@harshmangalam

**Comment by ashishpetwal** [comment]
Thanks for assigning will follow up soon !

**Comment by arsen1c** [comment]
Hi, I can work on this issue if it is not fixed already.

**Comment by arsen1c** [comment]
Hi, you can assign me this task @harshmangalam

**Comment by harshmangalam** [comment]
Issues resolved
