### ISSUE TITLE
Add image upload size limit 

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#23]
Limit image size  during upload and show warning message.
- Post ,Group Post and Cover image  - Limit image size 2mb
- Other all -  Limit image size 1mb

Image upload is a shared component that are used everywhere from profile pic change to post image upload hence accept image limit  from props

**Comment by RahulSankhla312** [comment]
hey @harshmangalam could you assign this issue to me.

**Comment by harshmangalam** [comment]
Sure

**Comment by arsen1c** [comment]
Hey, @harshmangalam you can assign me this issue. Would be happy to resolve it.
