### ISSUE TITLE
Enhance My Friends page  accessibility

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#29]
Run lighthouse on `Friends` > `My Friends`  page and fix accessibility issues
- Background and foreground colors do not have a sufficient contrast ratio.
-  Heading elements are not in a sequentially-descending order

**Comment by Jem256** [comment]
hey, I would like to work on this

**Comment by harshmangalam** [comment]
Okay you can continue

**Comment by harshmangalam** [comment]
Fixed by @Jem256
