### ISSUE TITLE
Enhance Friends Suggestion page accessibility

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#30]
Run lighthouse on `Friends` > `Suggestions` and fix accessibility issues
- Background and foreground colors do not have a sufficient contrast ratio.
- Heading elements are not in a sequentially-descending order

**Comment by ahmedsilat44** [comment]
Hey @harshmangalam I would like to work on this Issue, could you assign it to me. Thanks 😄

**Comment by Jem256** [comment]
hey can I work on this

**Comment by harshmangalam** [comment]
Sure
