### ISSUE TITLE
Add delete functionality for post comments

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#31]
Enhance post comment feature by adding delete comment 

- Show delete btn to only comment author
- To delete comment make api call to `/comments/:commentId`
- After comment deleted fetch all comments to show updated comments

**Comment by nore-dev** [comment]
can you assign it to me

**Comment by harshmangalam** [comment]
Okay

**Comment by nore-dev** [comment]
Is there a DELETE method required to delete comments on the server? I looked at the server code but couldn't find it

**Comment by harshmangalam** [comment]
I already open one issues regarding that in server
https://github.com/harshmangalam/hydrogen-nodejs-server/issues/5
