### ISSUE TITLE
[FEATURE] Add open graph image

### ISSUE THREAD

**Issue by Nakamcode** [harshmangalam/hydrogen-solidjs-client#36]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

### Below is how the website appeared when shared 👇👇👇
![captures_chrome-capture-2022-9-2 (4)](https://user-images.githubusercontent.com/89482825/193477511-cb793904-0413-44cc-a570-d21112b663e4.png)

**Comment by Ilikepizza2** [comment]
Hello there! 
May I be assigned this issue?

**Comment by Ilikepizza2** [comment]
Do you have any specific image in mind to add or should I add the landing page as the preview image?

**Comment by harshmangalam** [comment]
You can continue with landing page

**Comment by Ilikepizza2** [comment]
May I go on and add open graph title, url and other things also?

**Comment by harshmangalam** [comment]
Yes
