### ISSUE TITLE
Update post details

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#38]
Update post details inside Post comment
- When add new comment
- When remove any comment

**Comment by prateek-1606** [comment]
Hi @harshmangalam , can you explain this issue i would like to work on it.
Thanks

**Comment by harshmangalam** [comment]
In post detail there is two resource layer to fetch data from api 
- resource for fetch post details
- resource for fetch post comments

When any user will delete their comment or add new comment update both resource by calling their refetch method in this way data will be updated in frontend.

**Comment by prateek-1606** [comment]
@harshmangalam Thanks for clarifying. I would like to work on this please assign.

**Comment by harshmangalam** [comment]
FIxed by @prateek-1606
