### ISSUE TITLE
Remove extra comma

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#40]
After tagging  friends in create post showing extra comma `,` after last friend name

**Comment by jenniferabowd** [comment]
Mind assigning this to me? Also, would it be possible for you to screenshot the view to help me track down the component?

**Comment by harshmangalam** [comment]
![#40](https://user-images.githubusercontent.com/57381638/193503282-a53e07a6-bc1e-47bc-b4ae-cf62e5225691.png)

Here there is extra comma after last tagged name

**Comment by Gathin23** [comment]
U can assign me to the issue

**Comment by harshmangalam** [comment]
Fixed
