### ISSUE TITLE
Enhance create group post section

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#46]
Enhance create group post section

- Add spinner in create button
- Change disabled btn background

**Comment by Siddharth9890** [comment]
I would like to contribute. assign to me.

**Comment by harshmangalam** [comment]
Okay

**Comment by Siddharth9890** [comment]
Can you explain this with more detail so that i can start the work

**Comment by harshmangalam** [comment]
When you will open https://hydrogen-solid.vercel.app/groups/create_group_post  you will see that now Create button is showing `Creating group post...` when creating group  instead add spinner just like login button and add disable background color

**Comment by harshmangalam** [comment]
closed by @Siddharth9890
