### ISSUE TITLE
Fix avatar UI break

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#50]
![issue1](https://user-images.githubusercontent.com/57381638/193804037-ae4a6449-a484-44ac-bc8e-085c4ce77d9f.png)

Make avatar flex-none so that it will not break when content will increase.

**Comment by Utkarsh212** [comment]
Please assign this issue to me so that I can work on it

**Comment by harshmangalam** [comment]
Okay
