### ISSUE TITLE
Add admin info in group profile

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#51]
In group profile page  add admin info
- first name
- profile pic
- first name should be link which will navigate to admin profile

**Comment by Siddharth9890** [comment]
I can try it if you assign it to me

**Comment by Siddharth9890** [comment]
![image](https://user-images.githubusercontent.com/63333707/194001967-1e80e679-43bd-44e5-956c-0ebd870bebae.png)
Where should i place the profile pic should be placed so that i can work on css part then

**Comment by harshmangalam** [comment]
Right side is empty space you can put there

**Comment by harshmangalam** [comment]
![g1](https://user-images.githubusercontent.com/57381638/194003411-ebdc44b6-ddd7-4cba-87e5-2e29481c51ce.png)
Like this in tag left side profile right side name

**Comment by Siddharth9890** [comment]
![image](https://user-images.githubusercontent.com/63333707/194060109-ef6116f4-1295-4239-af5a-84e8fe4212c9.png)
Is this the correct position ?

**Comment by harshmangalam** [comment]
Yes

**Comment by Siddharth9890** [comment]
ok i raise a pr please check

**Comment by harshmangalam** [comment]
Done by @Siddharth9890
