### ISSUE TITLE
Add  debouncing optimization in Search

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#6]
Optimize search component of global navbar by add  Debouncing in search input.

**Comment by Yh010** [comment]
i would like to work on this issue

**Comment by ArinCodes** [comment]
I have resolved this issue please check My PULL request.. It's my first time contributing

**Comment by harshmangalam** [comment]
Done by @ArinCodes

**Comment by ArinCodes** [comment]
What happened ?
Can u please ellaborate the problem

**Comment by harshmangalam** [comment]
Yes debouncing is not working when i checked hence i revert the changes and reopened

**Comment by ArinCodes** [comment]
Debouncing is working it's just working for lower cased letter I tested 😅
