### ISSUE TITLE
Improve lighthouse accessibility of profile page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#60]
Improve lighthouse accessibility of profile page
- Image elements do not have [alt] attributes
- Background and foreground colors do not have a sufficient contrast ratio.
- Heading elements are not in a sequentially-descending order

**Comment by shivanshi-s** [comment]
Hi, I would like to give this a try!

**Comment by harshmangalam** [comment]
Great, i am assigning to you. you can proceed.
