### ISSUE TITLE
Add more feelings emoji

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#61]
In create post section `Add feeligs` add more emojis

**Comment by Akshay9607** [comment]
hey , i want to work on this , assign this to me

**Comment by Sourz-101** [comment]
Please assign this to me. I can do this.

**Comment by Sourz-101** [comment]
Can you elaborate on the problem

**Comment by harshmangalam** [comment]
You can start work i will merge pr from every one

**Comment by Akshay9607** [comment]
Hey , i added 9 feelings emojis , are they enough to merge my pr

**Comment by Akshay9607** [comment]
Hello , i added 9 more feeling emojis , are they enough to create pr , if any more changes let me know

**Comment by harshmangalam** [comment]
Yes you can make PR

**Comment by Akshay9607** [comment]
hey , i created a PR , but it is saying that , some checks are not successful , is this issue from my side or your side ?

**Comment by Akshay9607** [comment]
![PR_emoji](https://user-images.githubusercontent.com/114289275/194228603-5b41a5e9-41fd-4f95-86d7-24e0a6d9f736.png)

Can you please tell me , how to resolve this issue , is it from my side or you will be going to resolve this

**Comment by harshmangalam** [comment]
Every thing is ok this check is added for security reason
