### ISSUE TITLE
Better Password Validation

### ISSUE THREAD

**Issue by Ririio** [harshmangalam/hydrogen-solidjs-client#64]
I noticed you're not validating your password. Creating an account with a password of "123" works, but it doesn't sound secure. I suggest adding a validation that prevents the creation of an account if a password: 

- does not contain an uppercase
- does not have a number
- does not have a minimum length of 12

This ensures that it would be difficult for other people to access another user's account easily

I would like to work on this if possible

**Comment by harshmangalam** [comment]
Great idea i am assigning this task to you.

**Comment by Ririio** [comment]
Here's what I came up with in terms of how it would look like, tell if you think there's any that needs changing

**Missing Uppercase**
![image](https://user-images.githubusercontent.com/32577022/194335227-fd652742-30bc-42cb-ad01-0e49278d5904.png)

**Missing Number**
![image](https://user-images.githubusercontent.com/32577022/194335391-47a359f3-16bf-40f7-bfdf-585343208065.png)

**Comment by harshmangalam** [comment]
Awesome much more improved password security than before

**Comment by harshmangalam** [comment]
Added by @Ririio

**Comment by Ririio** [comment]
I noticed a problem when re-checking my code. It seems that it doesn't validate the length of the password. So for example I have a password "A1", it is still valid even though I specified that it should only be when the length is also equal or greater than 12.

I'm sending a pull request to fix this issue if you mind updating it
