### ISSUE TITLE
Add user details page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#77]
In profile page for now there is two tab `Posts` and `Friends` . 
 Add one more tab `About`  and add all user details  available using api.

**Comment by najeebkp** [comment]
Hi @harshmangalam please assign this to me

**Comment by harshmangalam** [comment]
Okay you can proceed

**Comment by notsosimppole** [comment]
Hi, I'd like to work on this. Please assign it to me.

**Comment by Naveen-Nair** [comment]
@harshmangalam Can i work on this issue?

**Comment by harshmangalam** [comment]
Okay you can proceed

**Comment by Naveen-Nair** [comment]
@harshmangalam  Could you review my PR #85? Thanks

**Comment by harshmangalam** [comment]
Added by @Naveen-Nair
