### ISSUE TITLE
Add tooltip in post privacy

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#78]
Add tooltip  for Post privacy icon in Post card.

**Comment by utkarsh4321** [comment]
can you assign this to me?

**Comment by harshmangalam** [comment]
Okay

**Comment by utkarsh4321** [comment]
![image](https://user-images.githubusercontent.com/30936607/194716460-391f81cc-c872-45b9-883f-c5ce48a81d2e.png)
Hi, you wanted to add a tooltip to this card? Can you please clarify?

**Comment by harshmangalam** [comment]
Yes , Here after post  created date there is icon this icon represent status of post. Add title in that icon.

**Comment by utkarsh4321** [comment]
that globe icon?

**Comment by harshmangalam** [comment]
Yes

**Comment by utkarsh4321** [comment]
so in tool tip i need to show created date when any body hover into it?

**Comment by harshmangalam** [comment]
No you need to show post status that is dynamic comming from api

**Comment by harshmangalam** [comment]
It can be public, friends, specific

**Comment by utkarsh4321** [comment]
so how i will decide it can you tell which one to show
what is the condition part of it

**Comment by utkarsh4321** [comment]
if it is created under a friends group then it will show friends like this what is the concept of it.

**Comment by harshmangalam** [comment]
There is no any condition you only need to show `post.audience` value in title

**Comment by harshmangalam** [comment]
See PostHeader.jsx component

**Comment by utkarsh4321** [comment]
ok

**Comment by harshmangalam** [comment]
Fixed by @utkarsh4321
