### ISSUE TITLE
Enhance  accessibility of friends suggestions

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#83]
Enhance lighthouse accessibility of `Friends Suggestions` page https://hydrogen-solid.vercel.app/friends/suggestions
- Background and foreground colors do not have a sufficient contrast ratio.
- Heading elements are not in a sequentially-descending orde

**Comment by richardnikolas** [comment]
@harshmangalam Could you assign this to me, please? I would like to contribute.

**Comment by harshmangalam** [comment]
Okay @richardnikolas  you can proceed

**Comment by harshmangalam** [comment]
fixed by @Jem256
