### ISSUE TITLE
Enhance create post page accessibility

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#88]
Improve lighthouse accessibility of Create Post page 
- Background and foreground colors do not have a sufficient contrast ratio.
- Links do not have a discernible name

**Comment by ayobamiseun** [comment]
can i contribute to this

**Comment by harshmangalam** [comment]
Okay

**Comment by harshmangalam** [comment]
Make pr i will merge
