### ISSUE TITLE
Add new tab in settings

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#9]
Inside `Settings and Privacy` add new tab below `Login history`  `Delete Account` when open Delete Account tab show warning message and delete button.

**Comment by Jem256** [comment]
hey, can I work on this?

**Comment by Jem256** [comment]
hey, @harshmangalam is there documentation for the backend API? I don't have the API route for deleting a user

**Comment by harshmangalam** [comment]
I already open one issues for that in backend project for now you can add UI part
https://github.com/harshmangalam/hydrogen-nodejs-server/issues/3

**Comment by Jem256** [comment]
alright. thank you

**Comment by harshmangalam** [comment]
Fixed by @Jem256
