### ISSUE TITLE
Show user details popup 

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-solidjs-client#91]
Show user details popup on mouseover user in post card

**Comment by billy-le** [comment]
I'm interested in working on this.

**Comment by harshmangalam** [comment]
Okay you can make PR i will merge.

**Comment by billy-le** [comment]
What details would you like me to include in the popup? Is there a design reference or should I create the ui?

**Comment by harshmangalam** [comment]
- User profile pic
- email
- firstName
- last seen if loggedout

**Comment by harshmangalam** [comment]
you can create ui according to your choice but use the existing theme.

**Comment by harshmangalam** [comment]
added by @billy-le
